### ISSUE TITLE
Duplicate Branch

### ISSUE THREAD

**Issue by AllieGie** [AllieGie/coding-challenges#1]
Created duplicate branch. Need to merge and delete one.

**Comment by JOSEPHToturial66** [comment]
What is the basical principle of python programs for the beginning student coding ?  Likewise first shutting gun

**Comment by mkarjun** [comment]
@AllieGie I found the issue through good first issue site, could you explain what to be done , like is it 
git merge source and  delete source-branch

**Comment by AllieGie** [comment]
> 

I did not merge and opted for deleting the duplicate branch. I figured since I'm just learning the platform it would be easy enough but I would not recommend doing that if your using an enterprise account or are in an org's main repository.
